// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/somiren-reference/Current.tsx": () => import("../components/mockups/somiren-reference/Current.tsx"),
  "./components/mockups/somiren-reference/Reference.tsx": () => import("../components/mockups/somiren-reference/Reference.tsx")
};
